package asuna.scala_tuple.tuple_support
object PlusToTuple4
    extends PlusToTuple_1_4
    with PlusToTuple_2_4
    with PlusToTuple_3_4
    with PlusToTuple_4_4
    with PlusToTuple_5_4
    with PlusToTuple_6_4
    with PlusToTuple_7_4
    with PlusToTuple_8_4
    with PlusToTuple_9_4
    with PlusToTuple_10_4
    with PlusToTuple_11_4
    with PlusToTuple_12_4
    with PlusToTuple_13_4
    with PlusToTuple_14_4
    with PlusToTuple_15_4
    with PlusToTuple_16_4
    with PlusToTuple_17_4
    with PlusToTuple_18_4
    with PlusToTuple_19_4
    with PlusToTuple_20_4
    with PlusToTuple_21_4
