package asuna.scala_tuple.tuple_support
object PlusToTuple5 extends PlusToTuple_1_5
    with PlusToTuple_2_5
    with PlusToTuple_3_5
    with PlusToTuple_4_5
    with PlusToTuple_5_5
    with PlusToTuple_6_5
    with PlusToTuple_7_5
    with PlusToTuple_8_5
    with PlusToTuple_9_5
    with PlusToTuple_10_5
    with PlusToTuple_11_5
    with PlusToTuple_12_5
    with PlusToTuple_13_5
    with PlusToTuple_14_5
    with PlusToTuple_15_5
    with PlusToTuple_16_5
    with PlusToTuple_17_5
    with PlusToTuple_18_5
    with PlusToTuple_19_5
    with PlusToTuple_20_5
    with PlusToTuple_21_5
