package asuna
final object PlusToTuple8 extends PlusToTuple_1_8
with PlusToTuple_2_8
with PlusToTuple_3_8
with PlusToTuple_4_8
with PlusToTuple_5_8
with PlusToTuple_6_8
with PlusToTuple_7_8
with PlusToTuple_8_8
with PlusToTuple_9_8
with PlusToTuple_10_8
with PlusToTuple_11_8
with PlusToTuple_12_8
with PlusToTuple_13_8
with PlusToTuple_14_8
