package zsg.scala_tuple.tuple_support
object PlusToTuple1
    extends PlusToTuple_1_1
    with PlusToTuple_2_1
    with PlusToTuple_3_1
    with PlusToTuple_4_1
    with PlusToTuple_5_1
    with PlusToTuple_6_1
    with PlusToTuple_7_1
    with PlusToTuple_8_1
    with PlusToTuple_9_1
    with PlusToTuple_10_1
    with PlusToTuple_11_1
    with PlusToTuple_12_1
    with PlusToTuple_13_1
    with PlusToTuple_14_1
    with PlusToTuple_15_1
    with PlusToTuple_16_1
    with PlusToTuple_17_1
    with PlusToTuple_18_1
    with PlusToTuple_19_1
    with PlusToTuple_20_1
    with PlusToTuple_21_1
    with PlusToTuple_22_1
