package zsg.scala_tuple
trait ScalaTupleImplicits
    extends tuple_support.ScalaTupleImplicits_2
    with tuple_support.ScalaTupleImplicits_3
    with tuple_support.ScalaTupleImplicits_4
    with tuple_support.ScalaTupleImplicits_5
    with tuple_support.ScalaTupleImplicits_6
    with tuple_support.ScalaTupleImplicits_7
    with tuple_support.ScalaTupleImplicits_8
    with tuple_support.ScalaTupleImplicits_9
    with tuple_support.ScalaTupleImplicits_10
    with tuple_support.ScalaTupleImplicits_11
    with tuple_support.ScalaTupleImplicits_12
    with tuple_support.ScalaTupleImplicits_13
    with tuple_support.ScalaTupleImplicits_14
    with tuple_support.ScalaTupleImplicits_15
    with tuple_support.ScalaTupleImplicits_16
    with tuple_support.ScalaTupleImplicits_17
    with tuple_support.ScalaTupleImplicits_18
    with tuple_support.ScalaTupleImplicits_19
    with tuple_support.ScalaTupleImplicits_20
    with tuple_support.ScalaTupleImplicits_21
    with tuple_support.ScalaTupleImplicits_22
object ScalaTupleImplicits extends ScalaTupleImplicits
