addSbtPlugin("com.geirsson"      % "sbt-scalafmt"  % "1.6.0-RC4")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.6.0-M3")
addSbtPlugin("com.typesafe.sbt"  % "sbt-twirl"     % "1.4.0-M2")
addSbtPlugin("org.foundweekends" % "sbt-bintray"   % "0.5.4")
addSbtPlugin("com.github.gseitz" % "sbt-release"   % "1.0.9")
