package zsg.scala_tuple.tuple_support
object HListPlus7 extends HListPlus_0_7
    with HListPlus_1_7
    with HListPlus_2_7
    with HListPlus_3_7
    with HListPlus_4_7
    with HListPlus_5_7
    with HListPlus_6_7
    with HListPlus_7_7
    with HListPlus_8_7
    with HListPlus_9_7
    with HListPlus_10_7
    with HListPlus_11_7
    with HListPlus_12_7
    with HListPlus_13_7
    with HListPlus_14_7
    with HListPlus_15_7
    with HListPlus_16_7
    with HListPlus_17_7
    with HListPlus_18_7
    with HListPlus_19_7
    with HListPlus_20_7
