package org.scalax.asuna.ii.item
class `Application can not load with index 1, please eat xyy.`  extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 2, please eat xyy.`  extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 3, please eat xyy.`  extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 4, please eat xyy.`  extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 5, please eat xyy.`  extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 6, please eat xyy.`  extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 7, please eat xyy.`  extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 8, please eat xyy.`  extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 9, please eat xyy.`  extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 10, please eat xyy.` extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 11, please eat xyy.` extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 12, please eat xyy.` extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 13, please eat xyy.` extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 14, please eat xyy.` extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 15, please eat xyy.` extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 16, please eat xyy.` extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 17, please eat xyy.` extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 18, please eat xyy.` extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 19, please eat xyy.` extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 20, please eat xyy.` extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 21, please eat xyy.` extends org.scalax.asuna.mapper.item.Message
class `Application can not load with index 22, please eat xyy.` extends org.scalax.asuna.mapper.item.Message
