package asuna.scala_tuple.tuple_support
object PlusToTuple2 extends PlusToTuple_1_2
    with PlusToTuple_2_2
    with PlusToTuple_3_2
    with PlusToTuple_4_2
    with PlusToTuple_5_2
    with PlusToTuple_6_2
    with PlusToTuple_7_2
    with PlusToTuple_8_2
    with PlusToTuple_9_2
    with PlusToTuple_10_2
    with PlusToTuple_11_2
    with PlusToTuple_12_2
    with PlusToTuple_13_2
    with PlusToTuple_14_2
    with PlusToTuple_15_2
    with PlusToTuple_16_2
    with PlusToTuple_17_2
    with PlusToTuple_18_2
    with PlusToTuple_19_2
    with PlusToTuple_20_2
    with PlusToTuple_21_2
