package zsg.scala_tuple.tuple_support
object HListPlus2 extends HListPlus_0_2
    with HListPlus_1_2
    with HListPlus_2_2
    with HListPlus_3_2
    with HListPlus_4_2
    with HListPlus_5_2
    with HListPlus_6_2
    with HListPlus_7_2
    with HListPlus_8_2
    with HListPlus_9_2
    with HListPlus_10_2
    with HListPlus_11_2
    with HListPlus_12_2
    with HListPlus_13_2
    with HListPlus_14_2
    with HListPlus_15_2
    with HListPlus_16_2
    with HListPlus_17_2
    with HListPlus_18_2
    with HListPlus_19_2
    with HListPlus_20_2
