package zsg.scala_tuple.tuple_support
object PlusToTuple7
    extends PlusToTuple_1_7
    with PlusToTuple_2_7
    with PlusToTuple_3_7
    with PlusToTuple_4_7
    with PlusToTuple_5_7
    with PlusToTuple_6_7
    with PlusToTuple_7_7
    with PlusToTuple_8_7
    with PlusToTuple_9_7
    with PlusToTuple_10_7
    with PlusToTuple_11_7
    with PlusToTuple_12_7
    with PlusToTuple_13_7
    with PlusToTuple_14_7
    with PlusToTuple_15_7
    with PlusToTuple_16_7
    with PlusToTuple_17_7
    with PlusToTuple_18_7
    with PlusToTuple_19_7
    with PlusToTuple_20_7
    with PlusToTuple_21_7
    with PlusToTuple_22_7
