addSbtPlugin("org.scalameta"      % "sbt-scalafmt"  % "2.4.2")
addSbtPlugin("org.scoverage"      % "sbt-scoverage" % "1.6.1")
addSbtPlugin("com.github.sbt"     % "sbt-release"   % "1.1.0")
addSbtPlugin("com.typesafe.sbt"   % "sbt-twirl"     % "1.5.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"       % "0.4.3")
