package asuna.scala_tuple.tuple_support
object PlusToTuple6 extends PlusToTuple_1_6
    with PlusToTuple_2_6
    with PlusToTuple_3_6
    with PlusToTuple_4_6
    with PlusToTuple_5_6
    with PlusToTuple_6_6
    with PlusToTuple_7_6
    with PlusToTuple_8_6
    with PlusToTuple_9_6
    with PlusToTuple_10_6
    with PlusToTuple_11_6
    with PlusToTuple_12_6
    with PlusToTuple_13_6
    with PlusToTuple_14_6
    with PlusToTuple_15_6
    with PlusToTuple_16_6
    with PlusToTuple_17_6
    with PlusToTuple_18_6
    with PlusToTuple_19_6
    with PlusToTuple_20_6
    with PlusToTuple_21_6
