package asuna.scala_tuple.tuple_support
object HListPlus3
    extends HListPlus_0_3
    with HListPlus_1_3
    with HListPlus_2_3
    with HListPlus_3_3
    with HListPlus_4_3
    with HListPlus_5_3
    with HListPlus_6_3
    with HListPlus_7_3
    with HListPlus_8_3
    with HListPlus_9_3
    with HListPlus_10_3
    with HListPlus_11_3
    with HListPlus_12_3
    with HListPlus_13_3
    with HListPlus_14_3
    with HListPlus_15_3
    with HListPlus_16_3
    with HListPlus_17_3
    with HListPlus_18_3
    with HListPlus_19_3
    with HListPlus_20_3
