package asuna.scala_tuple
trait ScalaTupleImplicits extends tuple_support.ScalaTupleImplicits_1_1
    with tuple_support.ScalaTupleImplicits_2_1
    with tuple_support.ScalaTupleImplicits_3_1
    with tuple_support.ScalaTupleImplicits_4_1
    with tuple_support.ScalaTupleImplicits_5_1
    with tuple_support.ScalaTupleImplicits_6_1
    with tuple_support.ScalaTupleImplicits_7_1
    with tuple_support.ScalaTupleImplicits_8_1
    with tuple_support.ScalaTupleImplicits_9_1
    with tuple_support.ScalaTupleImplicits_10_1
    with tuple_support.ScalaTupleImplicits_11_1
    with tuple_support.ScalaTupleImplicits_12_1
    with tuple_support.ScalaTupleImplicits_13_1
    with tuple_support.ScalaTupleImplicits_14_1
    with tuple_support.ScalaTupleImplicits_15_1
    with tuple_support.ScalaTupleImplicits_16_1
    with tuple_support.ScalaTupleImplicits_17_1
    with tuple_support.ScalaTupleImplicits_18_1
    with tuple_support.ScalaTupleImplicits_19_1
    with tuple_support.ScalaTupleImplicits_20_1
    with tuple_support.ScalaTupleImplicits_21_1
    with tuple_support.ScalaTupleImplicits_22_1
    with tuple_support.ScalaTupleImplicits_1_2
    with tuple_support.ScalaTupleImplicits_2_2
    with tuple_support.ScalaTupleImplicits_3_2
    with tuple_support.ScalaTupleImplicits_4_2
    with tuple_support.ScalaTupleImplicits_5_2
    with tuple_support.ScalaTupleImplicits_6_2
    with tuple_support.ScalaTupleImplicits_7_2
    with tuple_support.ScalaTupleImplicits_8_2
    with tuple_support.ScalaTupleImplicits_9_2
    with tuple_support.ScalaTupleImplicits_10_2
    with tuple_support.ScalaTupleImplicits_11_2
    with tuple_support.ScalaTupleImplicits_12_2
    with tuple_support.ScalaTupleImplicits_13_2
    with tuple_support.ScalaTupleImplicits_14_2
    with tuple_support.ScalaTupleImplicits_15_2
    with tuple_support.ScalaTupleImplicits_16_2
    with tuple_support.ScalaTupleImplicits_17_2
    with tuple_support.ScalaTupleImplicits_18_2
    with tuple_support.ScalaTupleImplicits_19_2
    with tuple_support.ScalaTupleImplicits_20_2
    with tuple_support.ScalaTupleImplicits_21_2
    with tuple_support.ScalaTupleImplicits_22_2
    with tuple_support.ScalaTupleImplicits_1_3
    with tuple_support.ScalaTupleImplicits_2_3
    with tuple_support.ScalaTupleImplicits_3_3
    with tuple_support.ScalaTupleImplicits_4_3
    with tuple_support.ScalaTupleImplicits_5_3
    with tuple_support.ScalaTupleImplicits_6_3
    with tuple_support.ScalaTupleImplicits_7_3
    with tuple_support.ScalaTupleImplicits_8_3
    with tuple_support.ScalaTupleImplicits_9_3
    with tuple_support.ScalaTupleImplicits_10_3
    with tuple_support.ScalaTupleImplicits_11_3
    with tuple_support.ScalaTupleImplicits_12_3
    with tuple_support.ScalaTupleImplicits_13_3
    with tuple_support.ScalaTupleImplicits_14_3
    with tuple_support.ScalaTupleImplicits_15_3
    with tuple_support.ScalaTupleImplicits_16_3
    with tuple_support.ScalaTupleImplicits_17_3
    with tuple_support.ScalaTupleImplicits_18_3
    with tuple_support.ScalaTupleImplicits_19_3
    with tuple_support.ScalaTupleImplicits_20_3
    with tuple_support.ScalaTupleImplicits_21_3
    with tuple_support.ScalaTupleImplicits_22_3
    with tuple_support.ScalaTupleImplicits_1_4
    with tuple_support.ScalaTupleImplicits_2_4
    with tuple_support.ScalaTupleImplicits_3_4
    with tuple_support.ScalaTupleImplicits_4_4
    with tuple_support.ScalaTupleImplicits_5_4
    with tuple_support.ScalaTupleImplicits_6_4
    with tuple_support.ScalaTupleImplicits_7_4
    with tuple_support.ScalaTupleImplicits_8_4
    with tuple_support.ScalaTupleImplicits_9_4
    with tuple_support.ScalaTupleImplicits_10_4
    with tuple_support.ScalaTupleImplicits_11_4
    with tuple_support.ScalaTupleImplicits_12_4
    with tuple_support.ScalaTupleImplicits_13_4
    with tuple_support.ScalaTupleImplicits_14_4
    with tuple_support.ScalaTupleImplicits_15_4
    with tuple_support.ScalaTupleImplicits_16_4
    with tuple_support.ScalaTupleImplicits_17_4
    with tuple_support.ScalaTupleImplicits_18_4
    with tuple_support.ScalaTupleImplicits_19_4
    with tuple_support.ScalaTupleImplicits_20_4
    with tuple_support.ScalaTupleImplicits_21_4
    with tuple_support.ScalaTupleImplicits_22_4
    with tuple_support.ScalaTupleImplicits_1_5
    with tuple_support.ScalaTupleImplicits_2_5
    with tuple_support.ScalaTupleImplicits_3_5
    with tuple_support.ScalaTupleImplicits_4_5
    with tuple_support.ScalaTupleImplicits_5_5
    with tuple_support.ScalaTupleImplicits_6_5
    with tuple_support.ScalaTupleImplicits_7_5
    with tuple_support.ScalaTupleImplicits_8_5
    with tuple_support.ScalaTupleImplicits_9_5
    with tuple_support.ScalaTupleImplicits_10_5
    with tuple_support.ScalaTupleImplicits_11_5
    with tuple_support.ScalaTupleImplicits_12_5
    with tuple_support.ScalaTupleImplicits_13_5
    with tuple_support.ScalaTupleImplicits_14_5
    with tuple_support.ScalaTupleImplicits_15_5
    with tuple_support.ScalaTupleImplicits_16_5
    with tuple_support.ScalaTupleImplicits_17_5
    with tuple_support.ScalaTupleImplicits_18_5
    with tuple_support.ScalaTupleImplicits_19_5
    with tuple_support.ScalaTupleImplicits_20_5
    with tuple_support.ScalaTupleImplicits_21_5
    with tuple_support.ScalaTupleImplicits_22_5
    with tuple_support.ScalaTupleImplicits_1_6
    with tuple_support.ScalaTupleImplicits_2_6
    with tuple_support.ScalaTupleImplicits_3_6
    with tuple_support.ScalaTupleImplicits_4_6
    with tuple_support.ScalaTupleImplicits_5_6
    with tuple_support.ScalaTupleImplicits_6_6
    with tuple_support.ScalaTupleImplicits_7_6
    with tuple_support.ScalaTupleImplicits_8_6
    with tuple_support.ScalaTupleImplicits_9_6
    with tuple_support.ScalaTupleImplicits_10_6
    with tuple_support.ScalaTupleImplicits_11_6
    with tuple_support.ScalaTupleImplicits_12_6
    with tuple_support.ScalaTupleImplicits_13_6
    with tuple_support.ScalaTupleImplicits_14_6
    with tuple_support.ScalaTupleImplicits_15_6
    with tuple_support.ScalaTupleImplicits_16_6
    with tuple_support.ScalaTupleImplicits_17_6
    with tuple_support.ScalaTupleImplicits_18_6
    with tuple_support.ScalaTupleImplicits_19_6
    with tuple_support.ScalaTupleImplicits_20_6
    with tuple_support.ScalaTupleImplicits_21_6
    with tuple_support.ScalaTupleImplicits_22_6
    with tuple_support.ScalaTupleImplicits_1_7
    with tuple_support.ScalaTupleImplicits_2_7
    with tuple_support.ScalaTupleImplicits_3_7
    with tuple_support.ScalaTupleImplicits_4_7
    with tuple_support.ScalaTupleImplicits_5_7
    with tuple_support.ScalaTupleImplicits_6_7
    with tuple_support.ScalaTupleImplicits_7_7
    with tuple_support.ScalaTupleImplicits_8_7
    with tuple_support.ScalaTupleImplicits_9_7
    with tuple_support.ScalaTupleImplicits_10_7
    with tuple_support.ScalaTupleImplicits_11_7
    with tuple_support.ScalaTupleImplicits_12_7
    with tuple_support.ScalaTupleImplicits_13_7
    with tuple_support.ScalaTupleImplicits_14_7
    with tuple_support.ScalaTupleImplicits_15_7
    with tuple_support.ScalaTupleImplicits_16_7
    with tuple_support.ScalaTupleImplicits_17_7
    with tuple_support.ScalaTupleImplicits_18_7
    with tuple_support.ScalaTupleImplicits_19_7
    with tuple_support.ScalaTupleImplicits_20_7
    with tuple_support.ScalaTupleImplicits_21_7
    with tuple_support.ScalaTupleImplicits_22_7
    with tuple_support.ScalaTupleImplicits_1_8
    with tuple_support.ScalaTupleImplicits_2_8
    with tuple_support.ScalaTupleImplicits_3_8
    with tuple_support.ScalaTupleImplicits_4_8
    with tuple_support.ScalaTupleImplicits_5_8
    with tuple_support.ScalaTupleImplicits_6_8
    with tuple_support.ScalaTupleImplicits_7_8
    with tuple_support.ScalaTupleImplicits_8_8
    with tuple_support.ScalaTupleImplicits_9_8
    with tuple_support.ScalaTupleImplicits_10_8
    with tuple_support.ScalaTupleImplicits_11_8
    with tuple_support.ScalaTupleImplicits_12_8
    with tuple_support.ScalaTupleImplicits_13_8
    with tuple_support.ScalaTupleImplicits_14_8
    with tuple_support.ScalaTupleImplicits_15_8
    with tuple_support.ScalaTupleImplicits_16_8
    with tuple_support.ScalaTupleImplicits_17_8
    with tuple_support.ScalaTupleImplicits_18_8
    with tuple_support.ScalaTupleImplicits_19_8
    with tuple_support.ScalaTupleImplicits_20_8
    with tuple_support.ScalaTupleImplicits_21_8
    with tuple_support.ScalaTupleImplicits_22_8
object ScalaTupleImplicits extends ScalaTupleImplicits
