package zsg.scala_tuple.tuple_support
object PlusToTuple3 extends PlusToTuple_1_3
    with PlusToTuple_2_3
    with PlusToTuple_3_3
    with PlusToTuple_4_3
    with PlusToTuple_5_3
    with PlusToTuple_6_3
    with PlusToTuple_7_3
    with PlusToTuple_8_3
    with PlusToTuple_9_3
    with PlusToTuple_10_3
    with PlusToTuple_11_3
    with PlusToTuple_12_3
    with PlusToTuple_13_3
    with PlusToTuple_14_3
    with PlusToTuple_15_3
    with PlusToTuple_16_3
    with PlusToTuple_17_3
    with PlusToTuple_18_3
    with PlusToTuple_19_3
    with PlusToTuple_20_3
    with PlusToTuple_21_3
    with PlusToTuple_22_3
