package zsg.macros.case_class_test
import zsg.macros.single.PropertyApply
import org.scalatest.funspec.AnyFunSpec
import org.scalatest.matchers.should.Matchers
class CaseClassTest202 extends AnyFunSpec with Matchers {
  case class Foo202(
    i1: Long,
    i2: Int,
    i3: Int,
    i4: Long,
    i5: Long = Long.MaxValue,
    i6: String,
    i7: Long,
    i8: Int,
    i9: Int,
    i10: Long,
    i11: Long = Long.MaxValue,
    i12: String,
    i13: Long,
    i14: Int,
    i15: Int,
    i16: Long,
    i17: Long = Long.MaxValue,
    i18: String,
    i19: Long,
    i20: Int,
    i21: Int,
    i22: Long,
    i23: Long = Long.MaxValue,
    i24: String,
    i25: Long,
    i26: Int,
    i27: Int,
    i28: Long,
    i29: Long = Long.MaxValue,
    i30: String,
    i31: Long,
    i32: Int,
    i33: Int,
    i34: Long,
    i35: Long = Long.MaxValue,
    i36: String,
    i37: Long,
    i38: Int,
    i39: Int,
    i40: Long,
    i41: Long = Long.MaxValue,
    i42: String,
    i43: Long,
    i44: Int,
    i45: Int,
    i46: Long,
    i47: Long = Long.MaxValue,
    i48: String,
    i49: Long,
    i50: Int,
    i51: Int,
    i52: Long,
    i53: Long = Long.MaxValue,
    i54: String,
    i55: Long,
    i56: Int,
    i57: Int,
    i58: Long,
    i59: Long = Long.MaxValue,
    i60: String,
    i61: Long,
    i62: Int,
    i63: Int,
    i64: Long,
    i65: Long = Long.MaxValue,
    i66: String,
    i67: Long,
    i68: Int,
    i69: Int,
    i70: Long,
    i71: Long = Long.MaxValue,
    i72: String,
    i73: Long,
    i74: Int,
    i75: Int,
    i76: Long,
    i77: Long = Long.MaxValue,
    i78: String,
    i79: Long,
    i80: Int,
    i81: Int,
    i82: Long,
    i83: Long = Long.MaxValue,
    i84: String,
    i85: Long,
    i86: Int,
    i87: Int,
    i88: Long,
    i89: Long = Long.MaxValue,
    i90: String,
    i91: Long,
    i92: Int,
    i93: Int,
    i94: Long,
    i95: Long = Long.MaxValue,
    i96: String,
    i97: Long,
    i98: Int,
    i99: Int,
    i100: Long,
    i101: Long = Long.MaxValue,
    i102: String,
    i103: Long,
    i104: Int,
    i105: Int,
    i106: Long,
    i107: Long = Long.MaxValue,
    i108: String,
    i109: Long,
    i110: Int,
    i111: Int,
    i112: Long,
    i113: Long = Long.MaxValue,
    i114: String,
    i115: Long,
    i116: Int,
    i117: Int,
    i118: Long,
    i119: Long = Long.MaxValue,
    i120: String,
    i121: Long,
    i122: Int,
    i123: Int,
    i124: Long,
    i125: Long = Long.MaxValue,
    i126: String,
    i127: Long,
    i128: Int,
    i129: Int,
    i130: Long,
    i131: Long = Long.MaxValue,
    i132: String,
    i133: Long,
    i134: Int,
    i135: Int,
    i136: Long,
    i137: Long = Long.MaxValue,
    i138: String,
    i139: Long,
    i140: Int,
    i141: Int,
    i142: Long,
    i143: Long = Long.MaxValue,
    i144: String,
    i145: Long,
    i146: Int,
    i147: Int,
    i148: Long,
    i149: Long = Long.MaxValue,
    i150: String,
    i151: Long,
    i152: Int,
    i153: Int,
    i154: Long,
    i155: Long = Long.MaxValue,
    i156: String,
    i157: Long,
    i158: Int,
    i159: Int,
    i160: Long,
    i161: Long = Long.MaxValue,
    i162: String,
    i163: Long,
    i164: Int,
    i165: Int,
    i166: Long,
    i167: Long = Long.MaxValue,
    i168: String,
    i169: Long,
    i170: Int,
    i171: Int,
    i172: Long,
    i173: Long = Long.MaxValue,
    i174: String,
    i175: Long,
    i176: Int,
    i177: Int,
    i178: Long,
    i179: Long = Long.MaxValue,
    i180: String,
    i181: Long,
    i182: Int,
    i183: Int,
    i184: Long,
    i185: Long = Long.MaxValue,
    i186: String,
    i187: Long,
    i188: Int,
    i189: Int,
    i190: Long,
    i191: Long = Long.MaxValue,
    i192: String,
    i193: Long,
    i194: Int,
    i195: Int,
    i196: Long,
    i197: Long = Long.MaxValue,
    i198: String,
    i199: Long,
    i200: Int,
    i201: Int,
    i202: Long
  ) {
    self =>
    def defaultValues: List[DefaultValue] =
      List(
        DefaultValue(value = Option.empty, fieldIndex = 1),
        DefaultValue(value = Option.empty, fieldIndex = 2),
        DefaultValue(value = Option.empty, fieldIndex = 3),
        DefaultValue(value = Option.empty, fieldIndex = 4),
        DefaultValue(value = Option(LongProperty(self.i5)), fieldIndex = 5),
        DefaultValue(value = Option.empty, fieldIndex = 6),
        DefaultValue(value = Option.empty, fieldIndex = 7),
        DefaultValue(value = Option.empty, fieldIndex = 8),
        DefaultValue(value = Option.empty, fieldIndex = 9),
        DefaultValue(value = Option.empty, fieldIndex = 10),
        DefaultValue(value = Option(LongProperty(self.i11)), fieldIndex = 11),
        DefaultValue(value = Option.empty, fieldIndex = 12),
        DefaultValue(value = Option.empty, fieldIndex = 13),
        DefaultValue(value = Option.empty, fieldIndex = 14),
        DefaultValue(value = Option.empty, fieldIndex = 15),
        DefaultValue(value = Option.empty, fieldIndex = 16),
        DefaultValue(value = Option(LongProperty(self.i17)), fieldIndex = 17),
        DefaultValue(value = Option.empty, fieldIndex = 18),
        DefaultValue(value = Option.empty, fieldIndex = 19),
        DefaultValue(value = Option.empty, fieldIndex = 20),
        DefaultValue(value = Option.empty, fieldIndex = 21),
        DefaultValue(value = Option.empty, fieldIndex = 22),
        DefaultValue(value = Option(LongProperty(self.i23)), fieldIndex = 23),
        DefaultValue(value = Option.empty, fieldIndex = 24),
        DefaultValue(value = Option.empty, fieldIndex = 25),
        DefaultValue(value = Option.empty, fieldIndex = 26),
        DefaultValue(value = Option.empty, fieldIndex = 27),
        DefaultValue(value = Option.empty, fieldIndex = 28),
        DefaultValue(value = Option(LongProperty(self.i29)), fieldIndex = 29),
        DefaultValue(value = Option.empty, fieldIndex = 30),
        DefaultValue(value = Option.empty, fieldIndex = 31),
        DefaultValue(value = Option.empty, fieldIndex = 32),
        DefaultValue(value = Option.empty, fieldIndex = 33),
        DefaultValue(value = Option.empty, fieldIndex = 34),
        DefaultValue(value = Option(LongProperty(self.i35)), fieldIndex = 35),
        DefaultValue(value = Option.empty, fieldIndex = 36),
        DefaultValue(value = Option.empty, fieldIndex = 37),
        DefaultValue(value = Option.empty, fieldIndex = 38),
        DefaultValue(value = Option.empty, fieldIndex = 39),
        DefaultValue(value = Option.empty, fieldIndex = 40),
        DefaultValue(value = Option(LongProperty(self.i41)), fieldIndex = 41),
        DefaultValue(value = Option.empty, fieldIndex = 42),
        DefaultValue(value = Option.empty, fieldIndex = 43),
        DefaultValue(value = Option.empty, fieldIndex = 44),
        DefaultValue(value = Option.empty, fieldIndex = 45),
        DefaultValue(value = Option.empty, fieldIndex = 46),
        DefaultValue(value = Option(LongProperty(self.i47)), fieldIndex = 47),
        DefaultValue(value = Option.empty, fieldIndex = 48),
        DefaultValue(value = Option.empty, fieldIndex = 49),
        DefaultValue(value = Option.empty, fieldIndex = 50),
        DefaultValue(value = Option.empty, fieldIndex = 51),
        DefaultValue(value = Option.empty, fieldIndex = 52),
        DefaultValue(value = Option(LongProperty(self.i53)), fieldIndex = 53),
        DefaultValue(value = Option.empty, fieldIndex = 54),
        DefaultValue(value = Option.empty, fieldIndex = 55),
        DefaultValue(value = Option.empty, fieldIndex = 56),
        DefaultValue(value = Option.empty, fieldIndex = 57),
        DefaultValue(value = Option.empty, fieldIndex = 58),
        DefaultValue(value = Option(LongProperty(self.i59)), fieldIndex = 59),
        DefaultValue(value = Option.empty, fieldIndex = 60),
        DefaultValue(value = Option.empty, fieldIndex = 61),
        DefaultValue(value = Option.empty, fieldIndex = 62),
        DefaultValue(value = Option.empty, fieldIndex = 63),
        DefaultValue(value = Option.empty, fieldIndex = 64),
        DefaultValue(value = Option(LongProperty(self.i65)), fieldIndex = 65),
        DefaultValue(value = Option.empty, fieldIndex = 66),
        DefaultValue(value = Option.empty, fieldIndex = 67),
        DefaultValue(value = Option.empty, fieldIndex = 68),
        DefaultValue(value = Option.empty, fieldIndex = 69),
        DefaultValue(value = Option.empty, fieldIndex = 70),
        DefaultValue(value = Option(LongProperty(self.i71)), fieldIndex = 71),
        DefaultValue(value = Option.empty, fieldIndex = 72),
        DefaultValue(value = Option.empty, fieldIndex = 73),
        DefaultValue(value = Option.empty, fieldIndex = 74),
        DefaultValue(value = Option.empty, fieldIndex = 75),
        DefaultValue(value = Option.empty, fieldIndex = 76),
        DefaultValue(value = Option(LongProperty(self.i77)), fieldIndex = 77),
        DefaultValue(value = Option.empty, fieldIndex = 78),
        DefaultValue(value = Option.empty, fieldIndex = 79),
        DefaultValue(value = Option.empty, fieldIndex = 80),
        DefaultValue(value = Option.empty, fieldIndex = 81),
        DefaultValue(value = Option.empty, fieldIndex = 82),
        DefaultValue(value = Option(LongProperty(self.i83)), fieldIndex = 83),
        DefaultValue(value = Option.empty, fieldIndex = 84),
        DefaultValue(value = Option.empty, fieldIndex = 85),
        DefaultValue(value = Option.empty, fieldIndex = 86),
        DefaultValue(value = Option.empty, fieldIndex = 87),
        DefaultValue(value = Option.empty, fieldIndex = 88),
        DefaultValue(value = Option(LongProperty(self.i89)), fieldIndex = 89),
        DefaultValue(value = Option.empty, fieldIndex = 90),
        DefaultValue(value = Option.empty, fieldIndex = 91),
        DefaultValue(value = Option.empty, fieldIndex = 92),
        DefaultValue(value = Option.empty, fieldIndex = 93),
        DefaultValue(value = Option.empty, fieldIndex = 94),
        DefaultValue(value = Option(LongProperty(self.i95)), fieldIndex = 95),
        DefaultValue(value = Option.empty, fieldIndex = 96),
        DefaultValue(value = Option.empty, fieldIndex = 97),
        DefaultValue(value = Option.empty, fieldIndex = 98),
        DefaultValue(value = Option.empty, fieldIndex = 99),
        DefaultValue(value = Option.empty, fieldIndex = 100),
        DefaultValue(value = Option(LongProperty(self.i101)), fieldIndex = 101),
        DefaultValue(value = Option.empty, fieldIndex = 102),
        DefaultValue(value = Option.empty, fieldIndex = 103),
        DefaultValue(value = Option.empty, fieldIndex = 104),
        DefaultValue(value = Option.empty, fieldIndex = 105),
        DefaultValue(value = Option.empty, fieldIndex = 106),
        DefaultValue(value = Option(LongProperty(self.i107)), fieldIndex = 107),
        DefaultValue(value = Option.empty, fieldIndex = 108),
        DefaultValue(value = Option.empty, fieldIndex = 109),
        DefaultValue(value = Option.empty, fieldIndex = 110),
        DefaultValue(value = Option.empty, fieldIndex = 111),
        DefaultValue(value = Option.empty, fieldIndex = 112),
        DefaultValue(value = Option(LongProperty(self.i113)), fieldIndex = 113),
        DefaultValue(value = Option.empty, fieldIndex = 114),
        DefaultValue(value = Option.empty, fieldIndex = 115),
        DefaultValue(value = Option.empty, fieldIndex = 116),
        DefaultValue(value = Option.empty, fieldIndex = 117),
        DefaultValue(value = Option.empty, fieldIndex = 118),
        DefaultValue(value = Option(LongProperty(self.i119)), fieldIndex = 119),
        DefaultValue(value = Option.empty, fieldIndex = 120),
        DefaultValue(value = Option.empty, fieldIndex = 121),
        DefaultValue(value = Option.empty, fieldIndex = 122),
        DefaultValue(value = Option.empty, fieldIndex = 123),
        DefaultValue(value = Option.empty, fieldIndex = 124),
        DefaultValue(value = Option(LongProperty(self.i125)), fieldIndex = 125),
        DefaultValue(value = Option.empty, fieldIndex = 126),
        DefaultValue(value = Option.empty, fieldIndex = 127),
        DefaultValue(value = Option.empty, fieldIndex = 128),
        DefaultValue(value = Option.empty, fieldIndex = 129),
        DefaultValue(value = Option.empty, fieldIndex = 130),
        DefaultValue(value = Option(LongProperty(self.i131)), fieldIndex = 131),
        DefaultValue(value = Option.empty, fieldIndex = 132),
        DefaultValue(value = Option.empty, fieldIndex = 133),
        DefaultValue(value = Option.empty, fieldIndex = 134),
        DefaultValue(value = Option.empty, fieldIndex = 135),
        DefaultValue(value = Option.empty, fieldIndex = 136),
        DefaultValue(value = Option(LongProperty(self.i137)), fieldIndex = 137),
        DefaultValue(value = Option.empty, fieldIndex = 138),
        DefaultValue(value = Option.empty, fieldIndex = 139),
        DefaultValue(value = Option.empty, fieldIndex = 140),
        DefaultValue(value = Option.empty, fieldIndex = 141),
        DefaultValue(value = Option.empty, fieldIndex = 142),
        DefaultValue(value = Option(LongProperty(self.i143)), fieldIndex = 143),
        DefaultValue(value = Option.empty, fieldIndex = 144),
        DefaultValue(value = Option.empty, fieldIndex = 145),
        DefaultValue(value = Option.empty, fieldIndex = 146),
        DefaultValue(value = Option.empty, fieldIndex = 147),
        DefaultValue(value = Option.empty, fieldIndex = 148),
        DefaultValue(value = Option(LongProperty(self.i149)), fieldIndex = 149),
        DefaultValue(value = Option.empty, fieldIndex = 150),
        DefaultValue(value = Option.empty, fieldIndex = 151),
        DefaultValue(value = Option.empty, fieldIndex = 152),
        DefaultValue(value = Option.empty, fieldIndex = 153),
        DefaultValue(value = Option.empty, fieldIndex = 154),
        DefaultValue(value = Option(LongProperty(self.i155)), fieldIndex = 155),
        DefaultValue(value = Option.empty, fieldIndex = 156),
        DefaultValue(value = Option.empty, fieldIndex = 157),
        DefaultValue(value = Option.empty, fieldIndex = 158),
        DefaultValue(value = Option.empty, fieldIndex = 159),
        DefaultValue(value = Option.empty, fieldIndex = 160),
        DefaultValue(value = Option(LongProperty(self.i161)), fieldIndex = 161),
        DefaultValue(value = Option.empty, fieldIndex = 162),
        DefaultValue(value = Option.empty, fieldIndex = 163),
        DefaultValue(value = Option.empty, fieldIndex = 164),
        DefaultValue(value = Option.empty, fieldIndex = 165),
        DefaultValue(value = Option.empty, fieldIndex = 166),
        DefaultValue(value = Option(LongProperty(self.i167)), fieldIndex = 167),
        DefaultValue(value = Option.empty, fieldIndex = 168),
        DefaultValue(value = Option.empty, fieldIndex = 169),
        DefaultValue(value = Option.empty, fieldIndex = 170),
        DefaultValue(value = Option.empty, fieldIndex = 171),
        DefaultValue(value = Option.empty, fieldIndex = 172),
        DefaultValue(value = Option(LongProperty(self.i173)), fieldIndex = 173),
        DefaultValue(value = Option.empty, fieldIndex = 174),
        DefaultValue(value = Option.empty, fieldIndex = 175),
        DefaultValue(value = Option.empty, fieldIndex = 176),
        DefaultValue(value = Option.empty, fieldIndex = 177),
        DefaultValue(value = Option.empty, fieldIndex = 178),
        DefaultValue(value = Option(LongProperty(self.i179)), fieldIndex = 179),
        DefaultValue(value = Option.empty, fieldIndex = 180),
        DefaultValue(value = Option.empty, fieldIndex = 181),
        DefaultValue(value = Option.empty, fieldIndex = 182),
        DefaultValue(value = Option.empty, fieldIndex = 183),
        DefaultValue(value = Option.empty, fieldIndex = 184),
        DefaultValue(value = Option(LongProperty(self.i185)), fieldIndex = 185),
        DefaultValue(value = Option.empty, fieldIndex = 186),
        DefaultValue(value = Option.empty, fieldIndex = 187),
        DefaultValue(value = Option.empty, fieldIndex = 188),
        DefaultValue(value = Option.empty, fieldIndex = 189),
        DefaultValue(value = Option.empty, fieldIndex = 190),
        DefaultValue(value = Option(LongProperty(self.i191)), fieldIndex = 191),
        DefaultValue(value = Option.empty, fieldIndex = 192),
        DefaultValue(value = Option.empty, fieldIndex = 193),
        DefaultValue(value = Option.empty, fieldIndex = 194),
        DefaultValue(value = Option.empty, fieldIndex = 195),
        DefaultValue(value = Option.empty, fieldIndex = 196),
        DefaultValue(value = Option(LongProperty(self.i197)), fieldIndex = 197),
        DefaultValue(value = Option.empty, fieldIndex = 198),
        DefaultValue(value = Option.empty, fieldIndex = 199),
        DefaultValue(value = Option.empty, fieldIndex = 200),
        DefaultValue(value = Option.empty, fieldIndex = 201),
        DefaultValue(value = Option.empty, fieldIndex = 202)
      )
    def fieldInfo: List[FieldModel] =
      List(
        FieldModel(value = LongProperty(self.i1), fieldIndex = 1, fieldName = "i1", typeName = "Long"),
        FieldModel(value = IntProperty(self.i2), fieldIndex = 2, fieldName = "i2", typeName = "Int"),
        FieldModel(value = IntProperty(self.i3), fieldIndex = 3, fieldName = "i3", typeName = "Int"),
        FieldModel(value = LongProperty(self.i4), fieldIndex = 4, fieldName = "i4", typeName = "Long"),
        FieldModel(value = LongProperty(self.i5), fieldIndex = 5, fieldName = "i5", typeName = "Long"),
        FieldModel(value = StringProperty(self.i6), fieldIndex = 6, fieldName = "i6", typeName = "String"),
        FieldModel(value = LongProperty(self.i7), fieldIndex = 7, fieldName = "i7", typeName = "Long"),
        FieldModel(value = IntProperty(self.i8), fieldIndex = 8, fieldName = "i8", typeName = "Int"),
        FieldModel(value = IntProperty(self.i9), fieldIndex = 9, fieldName = "i9", typeName = "Int"),
        FieldModel(value = LongProperty(self.i10), fieldIndex = 10, fieldName = "i10", typeName = "Long"),
        FieldModel(value = LongProperty(self.i11), fieldIndex = 11, fieldName = "i11", typeName = "Long"),
        FieldModel(value = StringProperty(self.i12), fieldIndex = 12, fieldName = "i12", typeName = "String"),
        FieldModel(value = LongProperty(self.i13), fieldIndex = 13, fieldName = "i13", typeName = "Long"),
        FieldModel(value = IntProperty(self.i14), fieldIndex = 14, fieldName = "i14", typeName = "Int"),
        FieldModel(value = IntProperty(self.i15), fieldIndex = 15, fieldName = "i15", typeName = "Int"),
        FieldModel(value = LongProperty(self.i16), fieldIndex = 16, fieldName = "i16", typeName = "Long"),
        FieldModel(value = LongProperty(self.i17), fieldIndex = 17, fieldName = "i17", typeName = "Long"),
        FieldModel(value = StringProperty(self.i18), fieldIndex = 18, fieldName = "i18", typeName = "String"),
        FieldModel(value = LongProperty(self.i19), fieldIndex = 19, fieldName = "i19", typeName = "Long"),
        FieldModel(value = IntProperty(self.i20), fieldIndex = 20, fieldName = "i20", typeName = "Int"),
        FieldModel(value = IntProperty(self.i21), fieldIndex = 21, fieldName = "i21", typeName = "Int"),
        FieldModel(value = LongProperty(self.i22), fieldIndex = 22, fieldName = "i22", typeName = "Long"),
        FieldModel(value = LongProperty(self.i23), fieldIndex = 23, fieldName = "i23", typeName = "Long"),
        FieldModel(value = StringProperty(self.i24), fieldIndex = 24, fieldName = "i24", typeName = "String"),
        FieldModel(value = LongProperty(self.i25), fieldIndex = 25, fieldName = "i25", typeName = "Long"),
        FieldModel(value = IntProperty(self.i26), fieldIndex = 26, fieldName = "i26", typeName = "Int"),
        FieldModel(value = IntProperty(self.i27), fieldIndex = 27, fieldName = "i27", typeName = "Int"),
        FieldModel(value = LongProperty(self.i28), fieldIndex = 28, fieldName = "i28", typeName = "Long"),
        FieldModel(value = LongProperty(self.i29), fieldIndex = 29, fieldName = "i29", typeName = "Long"),
        FieldModel(value = StringProperty(self.i30), fieldIndex = 30, fieldName = "i30", typeName = "String"),
        FieldModel(value = LongProperty(self.i31), fieldIndex = 31, fieldName = "i31", typeName = "Long"),
        FieldModel(value = IntProperty(self.i32), fieldIndex = 32, fieldName = "i32", typeName = "Int"),
        FieldModel(value = IntProperty(self.i33), fieldIndex = 33, fieldName = "i33", typeName = "Int"),
        FieldModel(value = LongProperty(self.i34), fieldIndex = 34, fieldName = "i34", typeName = "Long"),
        FieldModel(value = LongProperty(self.i35), fieldIndex = 35, fieldName = "i35", typeName = "Long"),
        FieldModel(value = StringProperty(self.i36), fieldIndex = 36, fieldName = "i36", typeName = "String"),
        FieldModel(value = LongProperty(self.i37), fieldIndex = 37, fieldName = "i37", typeName = "Long"),
        FieldModel(value = IntProperty(self.i38), fieldIndex = 38, fieldName = "i38", typeName = "Int"),
        FieldModel(value = IntProperty(self.i39), fieldIndex = 39, fieldName = "i39", typeName = "Int"),
        FieldModel(value = LongProperty(self.i40), fieldIndex = 40, fieldName = "i40", typeName = "Long"),
        FieldModel(value = LongProperty(self.i41), fieldIndex = 41, fieldName = "i41", typeName = "Long"),
        FieldModel(value = StringProperty(self.i42), fieldIndex = 42, fieldName = "i42", typeName = "String"),
        FieldModel(value = LongProperty(self.i43), fieldIndex = 43, fieldName = "i43", typeName = "Long"),
        FieldModel(value = IntProperty(self.i44), fieldIndex = 44, fieldName = "i44", typeName = "Int"),
        FieldModel(value = IntProperty(self.i45), fieldIndex = 45, fieldName = "i45", typeName = "Int"),
        FieldModel(value = LongProperty(self.i46), fieldIndex = 46, fieldName = "i46", typeName = "Long"),
        FieldModel(value = LongProperty(self.i47), fieldIndex = 47, fieldName = "i47", typeName = "Long"),
        FieldModel(value = StringProperty(self.i48), fieldIndex = 48, fieldName = "i48", typeName = "String"),
        FieldModel(value = LongProperty(self.i49), fieldIndex = 49, fieldName = "i49", typeName = "Long"),
        FieldModel(value = IntProperty(self.i50), fieldIndex = 50, fieldName = "i50", typeName = "Int"),
        FieldModel(value = IntProperty(self.i51), fieldIndex = 51, fieldName = "i51", typeName = "Int"),
        FieldModel(value = LongProperty(self.i52), fieldIndex = 52, fieldName = "i52", typeName = "Long"),
        FieldModel(value = LongProperty(self.i53), fieldIndex = 53, fieldName = "i53", typeName = "Long"),
        FieldModel(value = StringProperty(self.i54), fieldIndex = 54, fieldName = "i54", typeName = "String"),
        FieldModel(value = LongProperty(self.i55), fieldIndex = 55, fieldName = "i55", typeName = "Long"),
        FieldModel(value = IntProperty(self.i56), fieldIndex = 56, fieldName = "i56", typeName = "Int"),
        FieldModel(value = IntProperty(self.i57), fieldIndex = 57, fieldName = "i57", typeName = "Int"),
        FieldModel(value = LongProperty(self.i58), fieldIndex = 58, fieldName = "i58", typeName = "Long"),
        FieldModel(value = LongProperty(self.i59), fieldIndex = 59, fieldName = "i59", typeName = "Long"),
        FieldModel(value = StringProperty(self.i60), fieldIndex = 60, fieldName = "i60", typeName = "String"),
        FieldModel(value = LongProperty(self.i61), fieldIndex = 61, fieldName = "i61", typeName = "Long"),
        FieldModel(value = IntProperty(self.i62), fieldIndex = 62, fieldName = "i62", typeName = "Int"),
        FieldModel(value = IntProperty(self.i63), fieldIndex = 63, fieldName = "i63", typeName = "Int"),
        FieldModel(value = LongProperty(self.i64), fieldIndex = 64, fieldName = "i64", typeName = "Long"),
        FieldModel(value = LongProperty(self.i65), fieldIndex = 65, fieldName = "i65", typeName = "Long"),
        FieldModel(value = StringProperty(self.i66), fieldIndex = 66, fieldName = "i66", typeName = "String"),
        FieldModel(value = LongProperty(self.i67), fieldIndex = 67, fieldName = "i67", typeName = "Long"),
        FieldModel(value = IntProperty(self.i68), fieldIndex = 68, fieldName = "i68", typeName = "Int"),
        FieldModel(value = IntProperty(self.i69), fieldIndex = 69, fieldName = "i69", typeName = "Int"),
        FieldModel(value = LongProperty(self.i70), fieldIndex = 70, fieldName = "i70", typeName = "Long"),
        FieldModel(value = LongProperty(self.i71), fieldIndex = 71, fieldName = "i71", typeName = "Long"),
        FieldModel(value = StringProperty(self.i72), fieldIndex = 72, fieldName = "i72", typeName = "String"),
        FieldModel(value = LongProperty(self.i73), fieldIndex = 73, fieldName = "i73", typeName = "Long"),
        FieldModel(value = IntProperty(self.i74), fieldIndex = 74, fieldName = "i74", typeName = "Int"),
        FieldModel(value = IntProperty(self.i75), fieldIndex = 75, fieldName = "i75", typeName = "Int"),
        FieldModel(value = LongProperty(self.i76), fieldIndex = 76, fieldName = "i76", typeName = "Long"),
        FieldModel(value = LongProperty(self.i77), fieldIndex = 77, fieldName = "i77", typeName = "Long"),
        FieldModel(value = StringProperty(self.i78), fieldIndex = 78, fieldName = "i78", typeName = "String"),
        FieldModel(value = LongProperty(self.i79), fieldIndex = 79, fieldName = "i79", typeName = "Long"),
        FieldModel(value = IntProperty(self.i80), fieldIndex = 80, fieldName = "i80", typeName = "Int"),
        FieldModel(value = IntProperty(self.i81), fieldIndex = 81, fieldName = "i81", typeName = "Int"),
        FieldModel(value = LongProperty(self.i82), fieldIndex = 82, fieldName = "i82", typeName = "Long"),
        FieldModel(value = LongProperty(self.i83), fieldIndex = 83, fieldName = "i83", typeName = "Long"),
        FieldModel(value = StringProperty(self.i84), fieldIndex = 84, fieldName = "i84", typeName = "String"),
        FieldModel(value = LongProperty(self.i85), fieldIndex = 85, fieldName = "i85", typeName = "Long"),
        FieldModel(value = IntProperty(self.i86), fieldIndex = 86, fieldName = "i86", typeName = "Int"),
        FieldModel(value = IntProperty(self.i87), fieldIndex = 87, fieldName = "i87", typeName = "Int"),
        FieldModel(value = LongProperty(self.i88), fieldIndex = 88, fieldName = "i88", typeName = "Long"),
        FieldModel(value = LongProperty(self.i89), fieldIndex = 89, fieldName = "i89", typeName = "Long"),
        FieldModel(value = StringProperty(self.i90), fieldIndex = 90, fieldName = "i90", typeName = "String"),
        FieldModel(value = LongProperty(self.i91), fieldIndex = 91, fieldName = "i91", typeName = "Long"),
        FieldModel(value = IntProperty(self.i92), fieldIndex = 92, fieldName = "i92", typeName = "Int"),
        FieldModel(value = IntProperty(self.i93), fieldIndex = 93, fieldName = "i93", typeName = "Int"),
        FieldModel(value = LongProperty(self.i94), fieldIndex = 94, fieldName = "i94", typeName = "Long"),
        FieldModel(value = LongProperty(self.i95), fieldIndex = 95, fieldName = "i95", typeName = "Long"),
        FieldModel(value = StringProperty(self.i96), fieldIndex = 96, fieldName = "i96", typeName = "String"),
        FieldModel(value = LongProperty(self.i97), fieldIndex = 97, fieldName = "i97", typeName = "Long"),
        FieldModel(value = IntProperty(self.i98), fieldIndex = 98, fieldName = "i98", typeName = "Int"),
        FieldModel(value = IntProperty(self.i99), fieldIndex = 99, fieldName = "i99", typeName = "Int"),
        FieldModel(value = LongProperty(self.i100), fieldIndex = 100, fieldName = "i100", typeName = "Long"),
        FieldModel(value = LongProperty(self.i101), fieldIndex = 101, fieldName = "i101", typeName = "Long"),
        FieldModel(value = StringProperty(self.i102), fieldIndex = 102, fieldName = "i102", typeName = "String"),
        FieldModel(value = LongProperty(self.i103), fieldIndex = 103, fieldName = "i103", typeName = "Long"),
        FieldModel(value = IntProperty(self.i104), fieldIndex = 104, fieldName = "i104", typeName = "Int"),
        FieldModel(value = IntProperty(self.i105), fieldIndex = 105, fieldName = "i105", typeName = "Int"),
        FieldModel(value = LongProperty(self.i106), fieldIndex = 106, fieldName = "i106", typeName = "Long"),
        FieldModel(value = LongProperty(self.i107), fieldIndex = 107, fieldName = "i107", typeName = "Long"),
        FieldModel(value = StringProperty(self.i108), fieldIndex = 108, fieldName = "i108", typeName = "String"),
        FieldModel(value = LongProperty(self.i109), fieldIndex = 109, fieldName = "i109", typeName = "Long"),
        FieldModel(value = IntProperty(self.i110), fieldIndex = 110, fieldName = "i110", typeName = "Int"),
        FieldModel(value = IntProperty(self.i111), fieldIndex = 111, fieldName = "i111", typeName = "Int"),
        FieldModel(value = LongProperty(self.i112), fieldIndex = 112, fieldName = "i112", typeName = "Long"),
        FieldModel(value = LongProperty(self.i113), fieldIndex = 113, fieldName = "i113", typeName = "Long"),
        FieldModel(value = StringProperty(self.i114), fieldIndex = 114, fieldName = "i114", typeName = "String"),
        FieldModel(value = LongProperty(self.i115), fieldIndex = 115, fieldName = "i115", typeName = "Long"),
        FieldModel(value = IntProperty(self.i116), fieldIndex = 116, fieldName = "i116", typeName = "Int"),
        FieldModel(value = IntProperty(self.i117), fieldIndex = 117, fieldName = "i117", typeName = "Int"),
        FieldModel(value = LongProperty(self.i118), fieldIndex = 118, fieldName = "i118", typeName = "Long"),
        FieldModel(value = LongProperty(self.i119), fieldIndex = 119, fieldName = "i119", typeName = "Long"),
        FieldModel(value = StringProperty(self.i120), fieldIndex = 120, fieldName = "i120", typeName = "String"),
        FieldModel(value = LongProperty(self.i121), fieldIndex = 121, fieldName = "i121", typeName = "Long"),
        FieldModel(value = IntProperty(self.i122), fieldIndex = 122, fieldName = "i122", typeName = "Int"),
        FieldModel(value = IntProperty(self.i123), fieldIndex = 123, fieldName = "i123", typeName = "Int"),
        FieldModel(value = LongProperty(self.i124), fieldIndex = 124, fieldName = "i124", typeName = "Long"),
        FieldModel(value = LongProperty(self.i125), fieldIndex = 125, fieldName = "i125", typeName = "Long"),
        FieldModel(value = StringProperty(self.i126), fieldIndex = 126, fieldName = "i126", typeName = "String"),
        FieldModel(value = LongProperty(self.i127), fieldIndex = 127, fieldName = "i127", typeName = "Long"),
        FieldModel(value = IntProperty(self.i128), fieldIndex = 128, fieldName = "i128", typeName = "Int"),
        FieldModel(value = IntProperty(self.i129), fieldIndex = 129, fieldName = "i129", typeName = "Int"),
        FieldModel(value = LongProperty(self.i130), fieldIndex = 130, fieldName = "i130", typeName = "Long"),
        FieldModel(value = LongProperty(self.i131), fieldIndex = 131, fieldName = "i131", typeName = "Long"),
        FieldModel(value = StringProperty(self.i132), fieldIndex = 132, fieldName = "i132", typeName = "String"),
        FieldModel(value = LongProperty(self.i133), fieldIndex = 133, fieldName = "i133", typeName = "Long"),
        FieldModel(value = IntProperty(self.i134), fieldIndex = 134, fieldName = "i134", typeName = "Int"),
        FieldModel(value = IntProperty(self.i135), fieldIndex = 135, fieldName = "i135", typeName = "Int"),
        FieldModel(value = LongProperty(self.i136), fieldIndex = 136, fieldName = "i136", typeName = "Long"),
        FieldModel(value = LongProperty(self.i137), fieldIndex = 137, fieldName = "i137", typeName = "Long"),
        FieldModel(value = StringProperty(self.i138), fieldIndex = 138, fieldName = "i138", typeName = "String"),
        FieldModel(value = LongProperty(self.i139), fieldIndex = 139, fieldName = "i139", typeName = "Long"),
        FieldModel(value = IntProperty(self.i140), fieldIndex = 140, fieldName = "i140", typeName = "Int"),
        FieldModel(value = IntProperty(self.i141), fieldIndex = 141, fieldName = "i141", typeName = "Int"),
        FieldModel(value = LongProperty(self.i142), fieldIndex = 142, fieldName = "i142", typeName = "Long"),
        FieldModel(value = LongProperty(self.i143), fieldIndex = 143, fieldName = "i143", typeName = "Long"),
        FieldModel(value = StringProperty(self.i144), fieldIndex = 144, fieldName = "i144", typeName = "String"),
        FieldModel(value = LongProperty(self.i145), fieldIndex = 145, fieldName = "i145", typeName = "Long"),
        FieldModel(value = IntProperty(self.i146), fieldIndex = 146, fieldName = "i146", typeName = "Int"),
        FieldModel(value = IntProperty(self.i147), fieldIndex = 147, fieldName = "i147", typeName = "Int"),
        FieldModel(value = LongProperty(self.i148), fieldIndex = 148, fieldName = "i148", typeName = "Long"),
        FieldModel(value = LongProperty(self.i149), fieldIndex = 149, fieldName = "i149", typeName = "Long"),
        FieldModel(value = StringProperty(self.i150), fieldIndex = 150, fieldName = "i150", typeName = "String"),
        FieldModel(value = LongProperty(self.i151), fieldIndex = 151, fieldName = "i151", typeName = "Long"),
        FieldModel(value = IntProperty(self.i152), fieldIndex = 152, fieldName = "i152", typeName = "Int"),
        FieldModel(value = IntProperty(self.i153), fieldIndex = 153, fieldName = "i153", typeName = "Int"),
        FieldModel(value = LongProperty(self.i154), fieldIndex = 154, fieldName = "i154", typeName = "Long"),
        FieldModel(value = LongProperty(self.i155), fieldIndex = 155, fieldName = "i155", typeName = "Long"),
        FieldModel(value = StringProperty(self.i156), fieldIndex = 156, fieldName = "i156", typeName = "String"),
        FieldModel(value = LongProperty(self.i157), fieldIndex = 157, fieldName = "i157", typeName = "Long"),
        FieldModel(value = IntProperty(self.i158), fieldIndex = 158, fieldName = "i158", typeName = "Int"),
        FieldModel(value = IntProperty(self.i159), fieldIndex = 159, fieldName = "i159", typeName = "Int"),
        FieldModel(value = LongProperty(self.i160), fieldIndex = 160, fieldName = "i160", typeName = "Long"),
        FieldModel(value = LongProperty(self.i161), fieldIndex = 161, fieldName = "i161", typeName = "Long"),
        FieldModel(value = StringProperty(self.i162), fieldIndex = 162, fieldName = "i162", typeName = "String"),
        FieldModel(value = LongProperty(self.i163), fieldIndex = 163, fieldName = "i163", typeName = "Long"),
        FieldModel(value = IntProperty(self.i164), fieldIndex = 164, fieldName = "i164", typeName = "Int"),
        FieldModel(value = IntProperty(self.i165), fieldIndex = 165, fieldName = "i165", typeName = "Int"),
        FieldModel(value = LongProperty(self.i166), fieldIndex = 166, fieldName = "i166", typeName = "Long"),
        FieldModel(value = LongProperty(self.i167), fieldIndex = 167, fieldName = "i167", typeName = "Long"),
        FieldModel(value = StringProperty(self.i168), fieldIndex = 168, fieldName = "i168", typeName = "String"),
        FieldModel(value = LongProperty(self.i169), fieldIndex = 169, fieldName = "i169", typeName = "Long"),
        FieldModel(value = IntProperty(self.i170), fieldIndex = 170, fieldName = "i170", typeName = "Int"),
        FieldModel(value = IntProperty(self.i171), fieldIndex = 171, fieldName = "i171", typeName = "Int"),
        FieldModel(value = LongProperty(self.i172), fieldIndex = 172, fieldName = "i172", typeName = "Long"),
        FieldModel(value = LongProperty(self.i173), fieldIndex = 173, fieldName = "i173", typeName = "Long"),
        FieldModel(value = StringProperty(self.i174), fieldIndex = 174, fieldName = "i174", typeName = "String"),
        FieldModel(value = LongProperty(self.i175), fieldIndex = 175, fieldName = "i175", typeName = "Long"),
        FieldModel(value = IntProperty(self.i176), fieldIndex = 176, fieldName = "i176", typeName = "Int"),
        FieldModel(value = IntProperty(self.i177), fieldIndex = 177, fieldName = "i177", typeName = "Int"),
        FieldModel(value = LongProperty(self.i178), fieldIndex = 178, fieldName = "i178", typeName = "Long"),
        FieldModel(value = LongProperty(self.i179), fieldIndex = 179, fieldName = "i179", typeName = "Long"),
        FieldModel(value = StringProperty(self.i180), fieldIndex = 180, fieldName = "i180", typeName = "String"),
        FieldModel(value = LongProperty(self.i181), fieldIndex = 181, fieldName = "i181", typeName = "Long"),
        FieldModel(value = IntProperty(self.i182), fieldIndex = 182, fieldName = "i182", typeName = "Int"),
        FieldModel(value = IntProperty(self.i183), fieldIndex = 183, fieldName = "i183", typeName = "Int"),
        FieldModel(value = LongProperty(self.i184), fieldIndex = 184, fieldName = "i184", typeName = "Long"),
        FieldModel(value = LongProperty(self.i185), fieldIndex = 185, fieldName = "i185", typeName = "Long"),
        FieldModel(value = StringProperty(self.i186), fieldIndex = 186, fieldName = "i186", typeName = "String"),
        FieldModel(value = LongProperty(self.i187), fieldIndex = 187, fieldName = "i187", typeName = "Long"),
        FieldModel(value = IntProperty(self.i188), fieldIndex = 188, fieldName = "i188", typeName = "Int"),
        FieldModel(value = IntProperty(self.i189), fieldIndex = 189, fieldName = "i189", typeName = "Int"),
        FieldModel(value = LongProperty(self.i190), fieldIndex = 190, fieldName = "i190", typeName = "Long"),
        FieldModel(value = LongProperty(self.i191), fieldIndex = 191, fieldName = "i191", typeName = "Long"),
        FieldModel(value = StringProperty(self.i192), fieldIndex = 192, fieldName = "i192", typeName = "String"),
        FieldModel(value = LongProperty(self.i193), fieldIndex = 193, fieldName = "i193", typeName = "Long"),
        FieldModel(value = IntProperty(self.i194), fieldIndex = 194, fieldName = "i194", typeName = "Int"),
        FieldModel(value = IntProperty(self.i195), fieldIndex = 195, fieldName = "i195", typeName = "Int"),
        FieldModel(value = LongProperty(self.i196), fieldIndex = 196, fieldName = "i196", typeName = "Long"),
        FieldModel(value = LongProperty(self.i197), fieldIndex = 197, fieldName = "i197", typeName = "Long"),
        FieldModel(value = StringProperty(self.i198), fieldIndex = 198, fieldName = "i198", typeName = "String"),
        FieldModel(value = LongProperty(self.i199), fieldIndex = 199, fieldName = "i199", typeName = "Long"),
        FieldModel(value = IntProperty(self.i200), fieldIndex = 200, fieldName = "i200", typeName = "Int"),
        FieldModel(value = IntProperty(self.i201), fieldIndex = 201, fieldName = "i201", typeName = "Int"),
        FieldModel(value = LongProperty(self.i202), fieldIndex = 202, fieldName = "i202", typeName = "Long")
      )
    def reverseString: List[FieldModel] =
      List(
        FieldModel(value = LongProperty(self.i202), fieldIndex = 202, fieldName = "i202", typeName = "Long"),
        FieldModel(value = IntProperty(self.i201), fieldIndex = 201, fieldName = "i201", typeName = "Int"),
        FieldModel(value = IntProperty(self.i200), fieldIndex = 200, fieldName = "i200", typeName = "Int"),
        FieldModel(value = LongProperty(self.i199), fieldIndex = 199, fieldName = "i199", typeName = "Long"),
        FieldModel(value = StringProperty(self.i198), fieldIndex = 198, fieldName = "i198", typeName = "String"),
        FieldModel(value = LongProperty(self.i197), fieldIndex = 197, fieldName = "i197", typeName = "Long"),
        FieldModel(value = LongProperty(self.i196), fieldIndex = 196, fieldName = "i196", typeName = "Long"),
        FieldModel(value = IntProperty(self.i195), fieldIndex = 195, fieldName = "i195", typeName = "Int"),
        FieldModel(value = IntProperty(self.i194), fieldIndex = 194, fieldName = "i194", typeName = "Int"),
        FieldModel(value = LongProperty(self.i193), fieldIndex = 193, fieldName = "i193", typeName = "Long"),
        FieldModel(value = StringProperty(self.i192), fieldIndex = 192, fieldName = "i192", typeName = "String"),
        FieldModel(value = LongProperty(self.i191), fieldIndex = 191, fieldName = "i191", typeName = "Long"),
        FieldModel(value = LongProperty(self.i190), fieldIndex = 190, fieldName = "i190", typeName = "Long"),
        FieldModel(value = IntProperty(self.i189), fieldIndex = 189, fieldName = "i189", typeName = "Int"),
        FieldModel(value = IntProperty(self.i188), fieldIndex = 188, fieldName = "i188", typeName = "Int"),
        FieldModel(value = LongProperty(self.i187), fieldIndex = 187, fieldName = "i187", typeName = "Long"),
        FieldModel(value = StringProperty(self.i186), fieldIndex = 186, fieldName = "i186", typeName = "String"),
        FieldModel(value = LongProperty(self.i185), fieldIndex = 185, fieldName = "i185", typeName = "Long"),
        FieldModel(value = LongProperty(self.i184), fieldIndex = 184, fieldName = "i184", typeName = "Long"),
        FieldModel(value = IntProperty(self.i183), fieldIndex = 183, fieldName = "i183", typeName = "Int"),
        FieldModel(value = IntProperty(self.i182), fieldIndex = 182, fieldName = "i182", typeName = "Int"),
        FieldModel(value = LongProperty(self.i181), fieldIndex = 181, fieldName = "i181", typeName = "Long"),
        FieldModel(value = StringProperty(self.i180), fieldIndex = 180, fieldName = "i180", typeName = "String"),
        FieldModel(value = LongProperty(self.i179), fieldIndex = 179, fieldName = "i179", typeName = "Long"),
        FieldModel(value = LongProperty(self.i178), fieldIndex = 178, fieldName = "i178", typeName = "Long"),
        FieldModel(value = IntProperty(self.i177), fieldIndex = 177, fieldName = "i177", typeName = "Int"),
        FieldModel(value = IntProperty(self.i176), fieldIndex = 176, fieldName = "i176", typeName = "Int"),
        FieldModel(value = LongProperty(self.i175), fieldIndex = 175, fieldName = "i175", typeName = "Long"),
        FieldModel(value = StringProperty(self.i174), fieldIndex = 174, fieldName = "i174", typeName = "String"),
        FieldModel(value = LongProperty(self.i173), fieldIndex = 173, fieldName = "i173", typeName = "Long"),
        FieldModel(value = LongProperty(self.i172), fieldIndex = 172, fieldName = "i172", typeName = "Long"),
        FieldModel(value = IntProperty(self.i171), fieldIndex = 171, fieldName = "i171", typeName = "Int"),
        FieldModel(value = IntProperty(self.i170), fieldIndex = 170, fieldName = "i170", typeName = "Int"),
        FieldModel(value = LongProperty(self.i169), fieldIndex = 169, fieldName = "i169", typeName = "Long"),
        FieldModel(value = StringProperty(self.i168), fieldIndex = 168, fieldName = "i168", typeName = "String"),
        FieldModel(value = LongProperty(self.i167), fieldIndex = 167, fieldName = "i167", typeName = "Long"),
        FieldModel(value = LongProperty(self.i166), fieldIndex = 166, fieldName = "i166", typeName = "Long"),
        FieldModel(value = IntProperty(self.i165), fieldIndex = 165, fieldName = "i165", typeName = "Int"),
        FieldModel(value = IntProperty(self.i164), fieldIndex = 164, fieldName = "i164", typeName = "Int"),
        FieldModel(value = LongProperty(self.i163), fieldIndex = 163, fieldName = "i163", typeName = "Long"),
        FieldModel(value = StringProperty(self.i162), fieldIndex = 162, fieldName = "i162", typeName = "String"),
        FieldModel(value = LongProperty(self.i161), fieldIndex = 161, fieldName = "i161", typeName = "Long"),
        FieldModel(value = LongProperty(self.i160), fieldIndex = 160, fieldName = "i160", typeName = "Long"),
        FieldModel(value = IntProperty(self.i159), fieldIndex = 159, fieldName = "i159", typeName = "Int"),
        FieldModel(value = IntProperty(self.i158), fieldIndex = 158, fieldName = "i158", typeName = "Int"),
        FieldModel(value = LongProperty(self.i157), fieldIndex = 157, fieldName = "i157", typeName = "Long"),
        FieldModel(value = StringProperty(self.i156), fieldIndex = 156, fieldName = "i156", typeName = "String"),
        FieldModel(value = LongProperty(self.i155), fieldIndex = 155, fieldName = "i155", typeName = "Long"),
        FieldModel(value = LongProperty(self.i154), fieldIndex = 154, fieldName = "i154", typeName = "Long"),
        FieldModel(value = IntProperty(self.i153), fieldIndex = 153, fieldName = "i153", typeName = "Int"),
        FieldModel(value = IntProperty(self.i152), fieldIndex = 152, fieldName = "i152", typeName = "Int"),
        FieldModel(value = LongProperty(self.i151), fieldIndex = 151, fieldName = "i151", typeName = "Long"),
        FieldModel(value = StringProperty(self.i150), fieldIndex = 150, fieldName = "i150", typeName = "String"),
        FieldModel(value = LongProperty(self.i149), fieldIndex = 149, fieldName = "i149", typeName = "Long"),
        FieldModel(value = LongProperty(self.i148), fieldIndex = 148, fieldName = "i148", typeName = "Long"),
        FieldModel(value = IntProperty(self.i147), fieldIndex = 147, fieldName = "i147", typeName = "Int"),
        FieldModel(value = IntProperty(self.i146), fieldIndex = 146, fieldName = "i146", typeName = "Int"),
        FieldModel(value = LongProperty(self.i145), fieldIndex = 145, fieldName = "i145", typeName = "Long"),
        FieldModel(value = StringProperty(self.i144), fieldIndex = 144, fieldName = "i144", typeName = "String"),
        FieldModel(value = LongProperty(self.i143), fieldIndex = 143, fieldName = "i143", typeName = "Long"),
        FieldModel(value = LongProperty(self.i142), fieldIndex = 142, fieldName = "i142", typeName = "Long"),
        FieldModel(value = IntProperty(self.i141), fieldIndex = 141, fieldName = "i141", typeName = "Int"),
        FieldModel(value = IntProperty(self.i140), fieldIndex = 140, fieldName = "i140", typeName = "Int"),
        FieldModel(value = LongProperty(self.i139), fieldIndex = 139, fieldName = "i139", typeName = "Long"),
        FieldModel(value = StringProperty(self.i138), fieldIndex = 138, fieldName = "i138", typeName = "String"),
        FieldModel(value = LongProperty(self.i137), fieldIndex = 137, fieldName = "i137", typeName = "Long"),
        FieldModel(value = LongProperty(self.i136), fieldIndex = 136, fieldName = "i136", typeName = "Long"),
        FieldModel(value = IntProperty(self.i135), fieldIndex = 135, fieldName = "i135", typeName = "Int"),
        FieldModel(value = IntProperty(self.i134), fieldIndex = 134, fieldName = "i134", typeName = "Int"),
        FieldModel(value = LongProperty(self.i133), fieldIndex = 133, fieldName = "i133", typeName = "Long"),
        FieldModel(value = StringProperty(self.i132), fieldIndex = 132, fieldName = "i132", typeName = "String"),
        FieldModel(value = LongProperty(self.i131), fieldIndex = 131, fieldName = "i131", typeName = "Long"),
        FieldModel(value = LongProperty(self.i130), fieldIndex = 130, fieldName = "i130", typeName = "Long"),
        FieldModel(value = IntProperty(self.i129), fieldIndex = 129, fieldName = "i129", typeName = "Int"),
        FieldModel(value = IntProperty(self.i128), fieldIndex = 128, fieldName = "i128", typeName = "Int"),
        FieldModel(value = LongProperty(self.i127), fieldIndex = 127, fieldName = "i127", typeName = "Long"),
        FieldModel(value = StringProperty(self.i126), fieldIndex = 126, fieldName = "i126", typeName = "String"),
        FieldModel(value = LongProperty(self.i125), fieldIndex = 125, fieldName = "i125", typeName = "Long"),
        FieldModel(value = LongProperty(self.i124), fieldIndex = 124, fieldName = "i124", typeName = "Long"),
        FieldModel(value = IntProperty(self.i123), fieldIndex = 123, fieldName = "i123", typeName = "Int"),
        FieldModel(value = IntProperty(self.i122), fieldIndex = 122, fieldName = "i122", typeName = "Int"),
        FieldModel(value = LongProperty(self.i121), fieldIndex = 121, fieldName = "i121", typeName = "Long"),
        FieldModel(value = StringProperty(self.i120), fieldIndex = 120, fieldName = "i120", typeName = "String"),
        FieldModel(value = LongProperty(self.i119), fieldIndex = 119, fieldName = "i119", typeName = "Long"),
        FieldModel(value = LongProperty(self.i118), fieldIndex = 118, fieldName = "i118", typeName = "Long"),
        FieldModel(value = IntProperty(self.i117), fieldIndex = 117, fieldName = "i117", typeName = "Int"),
        FieldModel(value = IntProperty(self.i116), fieldIndex = 116, fieldName = "i116", typeName = "Int"),
        FieldModel(value = LongProperty(self.i115), fieldIndex = 115, fieldName = "i115", typeName = "Long"),
        FieldModel(value = StringProperty(self.i114), fieldIndex = 114, fieldName = "i114", typeName = "String"),
        FieldModel(value = LongProperty(self.i113), fieldIndex = 113, fieldName = "i113", typeName = "Long"),
        FieldModel(value = LongProperty(self.i112), fieldIndex = 112, fieldName = "i112", typeName = "Long"),
        FieldModel(value = IntProperty(self.i111), fieldIndex = 111, fieldName = "i111", typeName = "Int"),
        FieldModel(value = IntProperty(self.i110), fieldIndex = 110, fieldName = "i110", typeName = "Int"),
        FieldModel(value = LongProperty(self.i109), fieldIndex = 109, fieldName = "i109", typeName = "Long"),
        FieldModel(value = StringProperty(self.i108), fieldIndex = 108, fieldName = "i108", typeName = "String"),
        FieldModel(value = LongProperty(self.i107), fieldIndex = 107, fieldName = "i107", typeName = "Long"),
        FieldModel(value = LongProperty(self.i106), fieldIndex = 106, fieldName = "i106", typeName = "Long"),
        FieldModel(value = IntProperty(self.i105), fieldIndex = 105, fieldName = "i105", typeName = "Int"),
        FieldModel(value = IntProperty(self.i104), fieldIndex = 104, fieldName = "i104", typeName = "Int"),
        FieldModel(value = LongProperty(self.i103), fieldIndex = 103, fieldName = "i103", typeName = "Long"),
        FieldModel(value = StringProperty(self.i102), fieldIndex = 102, fieldName = "i102", typeName = "String"),
        FieldModel(value = LongProperty(self.i101), fieldIndex = 101, fieldName = "i101", typeName = "Long"),
        FieldModel(value = LongProperty(self.i100), fieldIndex = 100, fieldName = "i100", typeName = "Long"),
        FieldModel(value = IntProperty(self.i99), fieldIndex = 99, fieldName = "i99", typeName = "Int"),
        FieldModel(value = IntProperty(self.i98), fieldIndex = 98, fieldName = "i98", typeName = "Int"),
        FieldModel(value = LongProperty(self.i97), fieldIndex = 97, fieldName = "i97", typeName = "Long"),
        FieldModel(value = StringProperty(self.i96), fieldIndex = 96, fieldName = "i96", typeName = "String"),
        FieldModel(value = LongProperty(self.i95), fieldIndex = 95, fieldName = "i95", typeName = "Long"),
        FieldModel(value = LongProperty(self.i94), fieldIndex = 94, fieldName = "i94", typeName = "Long"),
        FieldModel(value = IntProperty(self.i93), fieldIndex = 93, fieldName = "i93", typeName = "Int"),
        FieldModel(value = IntProperty(self.i92), fieldIndex = 92, fieldName = "i92", typeName = "Int"),
        FieldModel(value = LongProperty(self.i91), fieldIndex = 91, fieldName = "i91", typeName = "Long"),
        FieldModel(value = StringProperty(self.i90), fieldIndex = 90, fieldName = "i90", typeName = "String"),
        FieldModel(value = LongProperty(self.i89), fieldIndex = 89, fieldName = "i89", typeName = "Long"),
        FieldModel(value = LongProperty(self.i88), fieldIndex = 88, fieldName = "i88", typeName = "Long"),
        FieldModel(value = IntProperty(self.i87), fieldIndex = 87, fieldName = "i87", typeName = "Int"),
        FieldModel(value = IntProperty(self.i86), fieldIndex = 86, fieldName = "i86", typeName = "Int"),
        FieldModel(value = LongProperty(self.i85), fieldIndex = 85, fieldName = "i85", typeName = "Long"),
        FieldModel(value = StringProperty(self.i84), fieldIndex = 84, fieldName = "i84", typeName = "String"),
        FieldModel(value = LongProperty(self.i83), fieldIndex = 83, fieldName = "i83", typeName = "Long"),
        FieldModel(value = LongProperty(self.i82), fieldIndex = 82, fieldName = "i82", typeName = "Long"),
        FieldModel(value = IntProperty(self.i81), fieldIndex = 81, fieldName = "i81", typeName = "Int"),
        FieldModel(value = IntProperty(self.i80), fieldIndex = 80, fieldName = "i80", typeName = "Int"),
        FieldModel(value = LongProperty(self.i79), fieldIndex = 79, fieldName = "i79", typeName = "Long"),
        FieldModel(value = StringProperty(self.i78), fieldIndex = 78, fieldName = "i78", typeName = "String"),
        FieldModel(value = LongProperty(self.i77), fieldIndex = 77, fieldName = "i77", typeName = "Long"),
        FieldModel(value = LongProperty(self.i76), fieldIndex = 76, fieldName = "i76", typeName = "Long"),
        FieldModel(value = IntProperty(self.i75), fieldIndex = 75, fieldName = "i75", typeName = "Int"),
        FieldModel(value = IntProperty(self.i74), fieldIndex = 74, fieldName = "i74", typeName = "Int"),
        FieldModel(value = LongProperty(self.i73), fieldIndex = 73, fieldName = "i73", typeName = "Long"),
        FieldModel(value = StringProperty(self.i72), fieldIndex = 72, fieldName = "i72", typeName = "String"),
        FieldModel(value = LongProperty(self.i71), fieldIndex = 71, fieldName = "i71", typeName = "Long"),
        FieldModel(value = LongProperty(self.i70), fieldIndex = 70, fieldName = "i70", typeName = "Long"),
        FieldModel(value = IntProperty(self.i69), fieldIndex = 69, fieldName = "i69", typeName = "Int"),
        FieldModel(value = IntProperty(self.i68), fieldIndex = 68, fieldName = "i68", typeName = "Int"),
        FieldModel(value = LongProperty(self.i67), fieldIndex = 67, fieldName = "i67", typeName = "Long"),
        FieldModel(value = StringProperty(self.i66), fieldIndex = 66, fieldName = "i66", typeName = "String"),
        FieldModel(value = LongProperty(self.i65), fieldIndex = 65, fieldName = "i65", typeName = "Long"),
        FieldModel(value = LongProperty(self.i64), fieldIndex = 64, fieldName = "i64", typeName = "Long"),
        FieldModel(value = IntProperty(self.i63), fieldIndex = 63, fieldName = "i63", typeName = "Int"),
        FieldModel(value = IntProperty(self.i62), fieldIndex = 62, fieldName = "i62", typeName = "Int"),
        FieldModel(value = LongProperty(self.i61), fieldIndex = 61, fieldName = "i61", typeName = "Long"),
        FieldModel(value = StringProperty(self.i60), fieldIndex = 60, fieldName = "i60", typeName = "String"),
        FieldModel(value = LongProperty(self.i59), fieldIndex = 59, fieldName = "i59", typeName = "Long"),
        FieldModel(value = LongProperty(self.i58), fieldIndex = 58, fieldName = "i58", typeName = "Long"),
        FieldModel(value = IntProperty(self.i57), fieldIndex = 57, fieldName = "i57", typeName = "Int"),
        FieldModel(value = IntProperty(self.i56), fieldIndex = 56, fieldName = "i56", typeName = "Int"),
        FieldModel(value = LongProperty(self.i55), fieldIndex = 55, fieldName = "i55", typeName = "Long"),
        FieldModel(value = StringProperty(self.i54), fieldIndex = 54, fieldName = "i54", typeName = "String"),
        FieldModel(value = LongProperty(self.i53), fieldIndex = 53, fieldName = "i53", typeName = "Long"),
        FieldModel(value = LongProperty(self.i52), fieldIndex = 52, fieldName = "i52", typeName = "Long"),
        FieldModel(value = IntProperty(self.i51), fieldIndex = 51, fieldName = "i51", typeName = "Int"),
        FieldModel(value = IntProperty(self.i50), fieldIndex = 50, fieldName = "i50", typeName = "Int"),
        FieldModel(value = LongProperty(self.i49), fieldIndex = 49, fieldName = "i49", typeName = "Long"),
        FieldModel(value = StringProperty(self.i48), fieldIndex = 48, fieldName = "i48", typeName = "String"),
        FieldModel(value = LongProperty(self.i47), fieldIndex = 47, fieldName = "i47", typeName = "Long"),
        FieldModel(value = LongProperty(self.i46), fieldIndex = 46, fieldName = "i46", typeName = "Long"),
        FieldModel(value = IntProperty(self.i45), fieldIndex = 45, fieldName = "i45", typeName = "Int"),
        FieldModel(value = IntProperty(self.i44), fieldIndex = 44, fieldName = "i44", typeName = "Int"),
        FieldModel(value = LongProperty(self.i43), fieldIndex = 43, fieldName = "i43", typeName = "Long"),
        FieldModel(value = StringProperty(self.i42), fieldIndex = 42, fieldName = "i42", typeName = "String"),
        FieldModel(value = LongProperty(self.i41), fieldIndex = 41, fieldName = "i41", typeName = "Long"),
        FieldModel(value = LongProperty(self.i40), fieldIndex = 40, fieldName = "i40", typeName = "Long"),
        FieldModel(value = IntProperty(self.i39), fieldIndex = 39, fieldName = "i39", typeName = "Int"),
        FieldModel(value = IntProperty(self.i38), fieldIndex = 38, fieldName = "i38", typeName = "Int"),
        FieldModel(value = LongProperty(self.i37), fieldIndex = 37, fieldName = "i37", typeName = "Long"),
        FieldModel(value = StringProperty(self.i36), fieldIndex = 36, fieldName = "i36", typeName = "String"),
        FieldModel(value = LongProperty(self.i35), fieldIndex = 35, fieldName = "i35", typeName = "Long"),
        FieldModel(value = LongProperty(self.i34), fieldIndex = 34, fieldName = "i34", typeName = "Long"),
        FieldModel(value = IntProperty(self.i33), fieldIndex = 33, fieldName = "i33", typeName = "Int"),
        FieldModel(value = IntProperty(self.i32), fieldIndex = 32, fieldName = "i32", typeName = "Int"),
        FieldModel(value = LongProperty(self.i31), fieldIndex = 31, fieldName = "i31", typeName = "Long"),
        FieldModel(value = StringProperty(self.i30), fieldIndex = 30, fieldName = "i30", typeName = "String"),
        FieldModel(value = LongProperty(self.i29), fieldIndex = 29, fieldName = "i29", typeName = "Long"),
        FieldModel(value = LongProperty(self.i28), fieldIndex = 28, fieldName = "i28", typeName = "Long"),
        FieldModel(value = IntProperty(self.i27), fieldIndex = 27, fieldName = "i27", typeName = "Int"),
        FieldModel(value = IntProperty(self.i26), fieldIndex = 26, fieldName = "i26", typeName = "Int"),
        FieldModel(value = LongProperty(self.i25), fieldIndex = 25, fieldName = "i25", typeName = "Long"),
        FieldModel(value = StringProperty(self.i24), fieldIndex = 24, fieldName = "i24", typeName = "String"),
        FieldModel(value = LongProperty(self.i23), fieldIndex = 23, fieldName = "i23", typeName = "Long"),
        FieldModel(value = LongProperty(self.i22), fieldIndex = 22, fieldName = "i22", typeName = "Long"),
        FieldModel(value = IntProperty(self.i21), fieldIndex = 21, fieldName = "i21", typeName = "Int"),
        FieldModel(value = IntProperty(self.i20), fieldIndex = 20, fieldName = "i20", typeName = "Int"),
        FieldModel(value = LongProperty(self.i19), fieldIndex = 19, fieldName = "i19", typeName = "Long"),
        FieldModel(value = StringProperty(self.i18), fieldIndex = 18, fieldName = "i18", typeName = "String"),
        FieldModel(value = LongProperty(self.i17), fieldIndex = 17, fieldName = "i17", typeName = "Long"),
        FieldModel(value = LongProperty(self.i16), fieldIndex = 16, fieldName = "i16", typeName = "Long"),
        FieldModel(value = IntProperty(self.i15), fieldIndex = 15, fieldName = "i15", typeName = "Int"),
        FieldModel(value = IntProperty(self.i14), fieldIndex = 14, fieldName = "i14", typeName = "Int"),
        FieldModel(value = LongProperty(self.i13), fieldIndex = 13, fieldName = "i13", typeName = "Long"),
        FieldModel(value = StringProperty(self.i12), fieldIndex = 12, fieldName = "i12", typeName = "String"),
        FieldModel(value = LongProperty(self.i11), fieldIndex = 11, fieldName = "i11", typeName = "Long"),
        FieldModel(value = LongProperty(self.i10), fieldIndex = 10, fieldName = "i10", typeName = "Long"),
        FieldModel(value = IntProperty(self.i9), fieldIndex = 9, fieldName = "i9", typeName = "Int"),
        FieldModel(value = IntProperty(self.i8), fieldIndex = 8, fieldName = "i8", typeName = "Int"),
        FieldModel(value = LongProperty(self.i7), fieldIndex = 7, fieldName = "i7", typeName = "Long"),
        FieldModel(value = StringProperty(self.i6), fieldIndex = 6, fieldName = "i6", typeName = "String"),
        FieldModel(value = LongProperty(self.i5), fieldIndex = 5, fieldName = "i5", typeName = "Long"),
        FieldModel(value = LongProperty(self.i4), fieldIndex = 4, fieldName = "i4", typeName = "Long"),
        FieldModel(value = IntProperty(self.i3), fieldIndex = 3, fieldName = "i3", typeName = "Int"),
        FieldModel(value = IntProperty(self.i2), fieldIndex = 2, fieldName = "i2", typeName = "Int"),
        FieldModel(value = LongProperty(self.i1), fieldIndex = 1, fieldName = "i1", typeName = "Long")
      )
  }
  val fooValue202 = Foo202(
    i1 = 225523422542L,
    i2 = 88,
    i3 = 82,
    i4 = 24564564L,
    i6 = "i1",
    i7 = 225523422542L,
    i8 = 88,
    i9 = 82,
    i10 = 24564564L,
    i12 = "i1",
    i13 = 225523422542L,
    i14 = 88,
    i15 = 82,
    i16 = 24564564L,
    i18 = "i1",
    i19 = 225523422542L,
    i20 = 88,
    i21 = 82,
    i22 = 24564564L,
    i24 = "i1",
    i25 = 225523422542L,
    i26 = 88,
    i27 = 82,
    i28 = 24564564L,
    i30 = "i1",
    i31 = 225523422542L,
    i32 = 88,
    i33 = 82,
    i34 = 24564564L,
    i36 = "i1",
    i37 = 225523422542L,
    i38 = 88,
    i39 = 82,
    i40 = 24564564L,
    i42 = "i1",
    i43 = 225523422542L,
    i44 = 88,
    i45 = 82,
    i46 = 24564564L,
    i48 = "i1",
    i49 = 225523422542L,
    i50 = 88,
    i51 = 82,
    i52 = 24564564L,
    i54 = "i1",
    i55 = 225523422542L,
    i56 = 88,
    i57 = 82,
    i58 = 24564564L,
    i60 = "i1",
    i61 = 225523422542L,
    i62 = 88,
    i63 = 82,
    i64 = 24564564L,
    i66 = "i1",
    i67 = 225523422542L,
    i68 = 88,
    i69 = 82,
    i70 = 24564564L,
    i72 = "i1",
    i73 = 225523422542L,
    i74 = 88,
    i75 = 82,
    i76 = 24564564L,
    i78 = "i1",
    i79 = 225523422542L,
    i80 = 88,
    i81 = 82,
    i82 = 24564564L,
    i84 = "i1",
    i85 = 225523422542L,
    i86 = 88,
    i87 = 82,
    i88 = 24564564L,
    i90 = "i1",
    i91 = 225523422542L,
    i92 = 88,
    i93 = 82,
    i94 = 24564564L,
    i96 = "i1",
    i97 = 225523422542L,
    i98 = 88,
    i99 = 82,
    i100 = 24564564L,
    i102 = "i1",
    i103 = 225523422542L,
    i104 = 88,
    i105 = 82,
    i106 = 24564564L,
    i108 = "i1",
    i109 = 225523422542L,
    i110 = 88,
    i111 = 82,
    i112 = 24564564L,
    i114 = "i1",
    i115 = 225523422542L,
    i116 = 88,
    i117 = 82,
    i118 = 24564564L,
    i120 = "i1",
    i121 = 225523422542L,
    i122 = 88,
    i123 = 82,
    i124 = 24564564L,
    i126 = "i1",
    i127 = 225523422542L,
    i128 = 88,
    i129 = 82,
    i130 = 24564564L,
    i132 = "i1",
    i133 = 225523422542L,
    i134 = 88,
    i135 = 82,
    i136 = 24564564L,
    i138 = "i1",
    i139 = 225523422542L,
    i140 = 88,
    i141 = 82,
    i142 = 24564564L,
    i144 = "i1",
    i145 = 225523422542L,
    i146 = 88,
    i147 = 82,
    i148 = 24564564L,
    i150 = "i1",
    i151 = 225523422542L,
    i152 = 88,
    i153 = 82,
    i154 = 24564564L,
    i156 = "i1",
    i157 = 225523422542L,
    i158 = 88,
    i159 = 82,
    i160 = 24564564L,
    i162 = "i1",
    i163 = 225523422542L,
    i164 = 88,
    i165 = 82,
    i166 = 24564564L,
    i168 = "i1",
    i169 = 225523422542L,
    i170 = 88,
    i171 = 82,
    i172 = 24564564L,
    i174 = "i1",
    i175 = 225523422542L,
    i176 = 88,
    i177 = 82,
    i178 = 24564564L,
    i180 = "i1",
    i181 = 225523422542L,
    i182 = 88,
    i183 = 82,
    i184 = 24564564L,
    i186 = "i1",
    i187 = 225523422542L,
    i188 = 88,
    i189 = 82,
    i190 = 24564564L,
    i192 = "i1",
    i193 = 225523422542L,
    i194 = 88,
    i195 = 82,
    i196 = 24564564L,
    i198 = "i1",
    i199 = 225523422542L,
    i200 = 88,
    i201 = 82,
    i202 = 24564564L
  )
  val ap202                                         = PropertyApply[Foo202]
  val fooEncoder202: ModelToString[Foo202]          = ModelToString.encoder
  val reverseFooEncoder202: ModelToString[Foo202]   = ModelToString.reverseEncoder
  val fooDecoder202: ModelFromString[Foo202]        = ModelFromString.decoder
  val reverseFooDecoder202: ModelFromString[Foo202] = ModelFromString.reverseDecoder
  describe("A case class by 202 length") {
    it("should generic to a encoder") {
      val str1 = fooEncoder202.mToString(fooValue202).mkString("|")
      str1 shouldBe fooValue202.toString
    }
    it("should generic to a reverse encoder") {
      val str2 = reverseFooEncoder202.mToString(fooValue202).mkString("|")
      str2 shouldBe fooValue202.reverseString
    }
    it("should generic to a decoder") {
      val (_, model1) = fooDecoder202.getData(fooValue202.toString)
      model1 shouldBe fooValue202
    }
    it("should generic to a reverse decoder") {
      val (_, model2) = reverseFooDecoder202.getData(fooValue202.reverseString)
      model2 shouldBe fooValue202
    }
  }
}
