package zsg.scala_tuple.tuple_support
object PlusToTuple8 extends PlusToTuple_1_8
    with PlusToTuple_2_8
    with PlusToTuple_3_8
    with PlusToTuple_4_8
    with PlusToTuple_5_8
    with PlusToTuple_6_8
    with PlusToTuple_7_8
    with PlusToTuple_8_8
    with PlusToTuple_9_8
    with PlusToTuple_10_8
    with PlusToTuple_11_8
    with PlusToTuple_12_8
    with PlusToTuple_13_8
    with PlusToTuple_14_8
    with PlusToTuple_15_8
    with PlusToTuple_16_8
    with PlusToTuple_17_8
    with PlusToTuple_18_8
    with PlusToTuple_19_8
    with PlusToTuple_20_8
    with PlusToTuple_21_8
    with PlusToTuple_22_8
